<a href="https://colab.research.google.com/github/BlackCurrantDS/DBSE_Project/blob/main/BreastCancer_data_read_v1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Attribute information: 
1. Class: no-recurrence-events, recurrence-events
2. age: 10-19, 20-29, 30-39, 40-49, 50-59, 60-69, 70-79, 80-89, 90-99.
3. menopause: lt40, ge40, premeno.
4. tumor-size: 0-4, 5-9, 10-14, 15-19, 20-24, 25-29, 30-34, 35-39, 40-44, 45-49, 50-54, 55-59.
5. inv-nodes: 0-2, 3-5, 6-8, 9-11, 12-14, 15-17, 18-20, 21-23, 24-26, 27-29, 30-32, 33-35, 36-39.
6. node-caps: yes, no.
7. deg-malig: 1, 2, 3.
8. breast: left, right.
9. breast-quad: left-up, left-low, right-up, right-low, central.
10. irradiat: yes, no.

In [2]:
import pandas as pd

df = pd.read_csv(
    'https://archive.ics.uci.edu/ml/machine-learning-databases/breast-cancer/breast-cancer.data', 
    sep=',', 
    header=None,
    names = ['class'
    ,'AGE'
    ,'menopause'
    ,'tumor-size'
    ,'inv-nodes'
    ,'node-caps'
    ,'deg-malig'
    ,'breast'
    ,'breast-quad'
    ,'irradiat']
  
)

print(df)

                    class    AGE menopause  ... breast breast-quad irradiat
0    no-recurrence-events  30-39   premeno  ...   left    left_low       no
1    no-recurrence-events  40-49   premeno  ...  right    right_up       no
2    no-recurrence-events  40-49   premeno  ...   left    left_low       no
3    no-recurrence-events  60-69      ge40  ...  right     left_up       no
4    no-recurrence-events  40-49   premeno  ...  right   right_low       no
..                    ...    ...       ...  ...    ...         ...      ...
281     recurrence-events  30-39   premeno  ...   left     left_up       no
282     recurrence-events  30-39   premeno  ...   left     left_up      yes
283     recurrence-events  60-69      ge40  ...  right     left_up       no
284     recurrence-events  40-49      ge40  ...   left    left_low       no
285     recurrence-events  50-59      ge40  ...   left    left_low       no

[286 rows x 10 columns]

In [3]:
df.to_csv("/content/drive/MyDrive/DataSets_for_Paper/bcancer_data_original.csv")

In [4]:
df.head(5)

                  class    AGE menopause  ... breast breast-quad irradiat
0  no-recurrence-events  30-39   premeno  ...   left    left_low       no
1  no-recurrence-events  40-49   premeno  ...  right    right_up       no
2  no-recurrence-events  40-49   premeno  ...   left    left_low       no
3  no-recurrence-events  60-69      ge40  ...  right     left_up       no
4  no-recurrence-events  40-49   premeno  ...  right   right_low       no

[5 rows x 10 columns]

In [6]:
df.columns[df.isna().any()].tolist()

[]

For rules generations

In [7]:
for i,n in enumerate(df.columns):
  #print(i,n)
  df[n] = 'A'+str(i)+'@' + df[n].astype(str)

In [8]:
df

                       class       AGE  ...   breast-quad irradiat
0    A0@no-recurrence-events  A1@30-39  ...   A8@left_low    A9@no
1    A0@no-recurrence-events  A1@40-49  ...   A8@right_up    A9@no
2    A0@no-recurrence-events  A1@40-49  ...   A8@left_low    A9@no
3    A0@no-recurrence-events  A1@60-69  ...    A8@left_up    A9@no
4    A0@no-recurrence-events  A1@40-49  ...  A8@right_low    A9@no
..                       ...       ...  ...           ...      ...
281     A0@recurrence-events  A1@30-39  ...    A8@left_up    A9@no
282     A0@recurrence-events  A1@30-39  ...    A8@left_up   A9@yes
283     A0@recurrence-events  A1@60-69  ...    A8@left_up    A9@no
284     A0@recurrence-events  A1@40-49  ...   A8@left_low    A9@no
285     A0@recurrence-events  A1@50-59  ...   A8@left_low    A9@no

[286 rows x 10 columns]

For RP-growth Data

In [9]:
uni = pd.DataFrame()
for col in df:
    uni= pd.concat([uni, pd.DataFrame(df[col].unique())], ignore_index=True)

In [10]:
uni

                          0
0   A0@no-recurrence-events
1      A0@recurrence-events
2                  A1@30-39
3                  A1@40-49
4                  A1@60-69
5                  A1@50-59
6                  A1@70-79
7                  A1@20-29
8                A2@premeno
9                   A2@ge40
10                  A2@lt40
11                 A3@30-34
12                 A3@20-24
13                 A3@15-19
14                   A3@0-4
15                 A3@25-29
16                 A3@50-54
17                 A3@10-14
18                 A3@40-44
19                 A3@35-39
20                   A3@5-9
21                 A3@45-49
22                   A4@0-2
23                   A4@6-8
24                  A4@9-11
25                   A4@3-5
26                 A4@15-17
27                 A4@12-14
28                 A4@24-26
29                    A5@no
30                   A5@yes
31                     A5@?
32                     A6@3
33                     A6@2
34                     A6@1
35                  A7@left
36                 A7@right
37              A8@left_low
38              A8@right_up
39               A8@left_up
40             A8@right_low
41               A8@central
42                     A8@?
43                    A9@no
44                   A9@yes

In [11]:
my_dict = uni.to_dict()

In [12]:
my_dict

{0: {0: 'A0@no-recurrence-events',
  1: 'A0@recurrence-events',
  2: 'A1@30-39',
  3: 'A1@40-49',
  4: 'A1@60-69',
  5: 'A1@50-59',
  6: 'A1@70-79',
  7: 'A1@20-29',
  8: 'A2@premeno',
  9: 'A2@ge40',
  10: 'A2@lt40',
  11: 'A3@30-34',
  12: 'A3@20-24',
  13: 'A3@15-19',
  14: 'A3@0-4',
  15: 'A3@25-29',
  16: 'A3@50-54',
  17: 'A3@10-14',
  18: 'A3@40-44',
  19: 'A3@35-39',
  20: 'A3@5-9',
  21: 'A3@45-49',
  22: 'A4@0-2',
  23: 'A4@6-8',
  24: 'A4@9-11',
  25: 'A4@3-5',
  26: 'A4@15-17',
  27: 'A4@12-14',
  28: 'A4@24-26',
  29: 'A5@no',
  30: 'A5@yes',
  31: 'A5@?',
  32: 'A6@3',
  33: 'A6@2',
  34: 'A6@1',
  35: 'A7@left',
  36: 'A7@right',
  37: 'A8@left_low',
  38: 'A8@right_up',
  39: 'A8@left_up',
  40: 'A8@right_low',
  41: 'A8@central',
  42: 'A8@?',
  43: 'A9@no',
  44: 'A9@yes'}}

In [13]:
my_dict = my_dict[0]

In [14]:
new_dict = dict((value, key) for key, value in my_dict.items())

In [15]:
for col in df:
    df[col] = df[col].replace(new_dict)

In [16]:
df

     class  AGE  menopause  ...  breast  breast-quad  irradiat
0        0    2          8  ...      35           37        43
1        0    3          8  ...      36           38        43
2        0    3          8  ...      35           37        43
3        0    4          9  ...      36           39        43
4        0    3          8  ...      36           40        43
..     ...  ...        ...  ...     ...          ...       ...
281      1    2          8  ...      35           39        43
282      1    2          8  ...      35           39        44
283      1    4          9  ...      36           39        43
284      1    3          9  ...      35           37        43
285      1    5          9  ...      35           37        43

[286 rows x 10 columns]

In [17]:
df.to_csv("/content/drive/MyDrive/DataSets_for_Paper/bcancer_data_to_numbers.csv")

In [ ]:
#removing sup
"""f = open('/content/output_hep_rp.txt','r')
lst = []
for line in f:
  line  = line.split("#", 1)
  
  line  = line[0]
  lst.append(line)
f.close()
f = open('/content/output_processed.txt','w')
for line in lst:
    f.write(line+'\n')
f.close()"""

Brining back to original

Converting unexpected rules to original attributes

In [ ]:
mapping = {
    
     'A10':'SPLEEN PALPABLE',
    'A11':'SPIDERS',
    'A12':'ASCITES',
    'A13':'VARICES',
    'A14':'ALK PHOSPHATE',
    'A15':'SGOT',
    'A16':'ALBUMIN',
    'A17':'PROTIME',
    'A18':'HISTOLOGY',
    
	'A0':'class'
    'A1':'AGE',
    'A2':'SEX',
    'A3':'STEROID',
    'A4':'ANTIVIRALS',
    'A5':'FATIGUE',
    'A6':'MALAISE',
    'A7':'ANOREXIA',
    'A8':'LIVER BIG',
    'A9':'LIVER FIRM'
   
           
           }

In [ ]:
import fileinput

text = "/content/drive/MyDrive/Clev_DataSet/RPGrowth/unexpected_rule_file_json.txt"
fields = mapping

lst = []
for line in fileinput.input(text):
    for field in fields:
        if field in line:
            line = line.replace(field, fields[field])
    lst.append(line)

print(lst)

['[["AGE2@2.0>class@1"],\n', '["cp@2.0,AGE3@3.0>class@0"],\n', '["cp@2.0>class@0"],\n', '["cp@2.0,AGE2@0.0>class@0"],\n', '["cp@2.0,exang@0.0,AGE2@0.0>class@0"],\n', '["cp@2.0,fbs@0.0>class@0"],\n', '["cp@2.0,exang@0.0>class@0"],\n', '["cp@2.0,fbs@0.0,exang@0.0>class@0"],\n', '["AGE2@1.0>class@1"],\n', '["cp@4.0,AGE2@1.0>class@1"],\n', '["cp@4.0,fbs@0.0,AGE2@1.0>class@1"],\n', '["SEX@1.0,cp@4.0,AGE2@1.0>class@1"],\n', '["fbs@0.0,AGE2@1.0>class@1"],\n', '["SEX@1.0,AGE2@1.0>class@1"],\n', '["SEX@1.0,fbs@0.0,AGE2@1.0>class@1"],\n', '["cp@3.0,AGE0@0.0>class@0"],\n', '["SEX@0.0,cp@3.0,AGE3@3.0>class@0"],\n', '["SEX@0.0,cp@3.0,exang@0.0,AGE3@3.0>class@0"],\n', '["SEX@0.0,cp@3.0,fbs@0.0,AGE3@3.0>class@0"],\n', '["SEX@0.0,cp@3.0>class@0"],\n', '["SEX@0.0,cp@3.0,exang@0.0>class@0"],\n', '["SEX@0.0,cp@3.0,fbs@0.0,exang@0.0>class@0"],\n', '["SEX@0.0,cp@3.0,fbs@0.0>class@0"],\n', '["cp@3.0,restecg@0.0,AGE3@3.0>class@0"],\n', '["cp@3.0,fbs@0.0,restecg@0.0,AGE3@3.0>class@0"],\n', '["cp@3.0,restecg@0.0,exang@0.0,AGE3@3.0>class@0"],\n', '["cp@3.0,restecg@0.0>class@0"],\n', '["cp@3.0,fbs@0.0,restecg@0.0>class@0"],\n', '["cp@3.0,restecg@0.0,exang@0.0>class@0"],\n', '["cp@3.0,fbs@0.0,restecg@0.0,exang@0.0>class@0"],\n', '["cp@3.0,restecg@0.0,AGE1@1.0>class@0"],\n', '["cp@3.0,restecg@0.0,exang@0.0,AGE1@1.0>class@0"],\n', '["cp@3.0,AGE1@1.0,AGE3@3.0>class@0"],\n', '["cp@3.0,fbs@0.0,AGE1@1.0,AGE3@3.0>class@0"],\n', '["cp@3.0,exang@0.0,AGE1@1.0,AGE3@3.0>class@0"],\n', '["cp@3.0,fbs@0.0,exang@0.0,AGE1@1.0,AGE3@3.0>class@0"],\n', '["cp@3.0,AGE1@1.0>class@0"],\n', '["cp@3.0,AGE1@1.0,AGE2@0.0>class@0"],\n', '["cp@3.0,exang@0.0,AGE1@1.0,AGE2@0.0>class@0"],\n', '["cp@3.0,fbs@0.0,AGE1@1.0>class@0"],\n', '["cp@3.0,exang@0.0,AGE1@1.0>class@0"],\n', '["cp@3.0,fbs@0.0,exang@0.0,AGE1@1.0>class@0"],\n', '["cp@3.0,AGE3@3.0>class@0"],\n', '["cp@3.0,AGE2@0.0,AGE3@3.0>class@0"],\n', '["cp@3.0,fbs@0.0,AGE2@0.0,AGE3@3.0>class@0"],\n', '["cp@3.0,exang@0.0,AGE2@0.0,AGE3@3.0>class@0"],\n', '["cp@3.0,fbs@0.0,exang@0.0,AGE2@0.0,AGE3@3.0>class@0"],\n', '["cp@3.0,fbs@0.0,AGE3@3.0>class@0"],\n', '["cp@3.0,exang@0.0,AGE3@3.0>class@0"],\n', '["cp@3.0,fbs@0.0,exang@0.0,AGE3@3.0>class@0"],\n', '["cp@3.0>class@0"],\n', '["SEX@1.0,cp@3.0>class@0"],\n', '["cp@3.0,AGE2@0.0>class@0"],\n', '["cp@3.0,fbs@0.0,AGE2@0.0>class@0"],\n', '["cp@3.0,exang@0.0,AGE2@0.0>class@0"],\n', '["cp@3.0,fbs@0.0,exang@0.0,AGE2@0.0>class@0"],\n', '["cp@3.0,fbs@0.0>class@0"],\n', '["cp@3.0,exang@0.0>class@0"],\n', '["SEX@1.0,cp@3.0,exang@0.0>class@0"],\n', '["cp@3.0,fbs@0.0,exang@0.0>class@0"],\n', '["SEX@0.0,AGE0@0.0>class@0"],\n', '["SEX@0.0,AGE0@0.0,AGE3@3.0>class@0"],\n', '["SEX@0.0,AGE1@1.0,AGE3@3.0>class@0"],\n', '["SEX@0.0,exang@0.0,AGE1@1.0,AGE3@3.0>class@0"],\n', '["SEX@0.0,fbs@0.0,exang@0.0,AGE1@1.0,AGE3@3.0>class@0"],\n', '["SEX@0.0,fbs@0.0,AGE1@1.0,AGE3@3.0>class@0"],\n', '["SEX@0.0,AGE1@1.0>class@0"],\n', '["SEX@0.0,exang@0.0,AGE1@1.0>class@0"],\n', '["SEX@0.0,fbs@0.0,exang@0.0,AGE1@1.0>class@0"],\n', '["SEX@0.0,fbs@0.0,AGE1@1.0>class@0"],\n', '["SEX@0.0,restecg@0.0>class@0"],\n', '["SEX@0.0,restecg@0.0,AGE2@0.0>class@0"],\n', '["SEX@0.0,fbs@0.0,restecg@0.0>class@0"],\n', '["SEX@0.0,restecg@0.0,exang@0.0>class@0"],\n', '["SEX@0.0,fbs@0.0,restecg@0.0,exang@0.0>class@0"],\n', '["SEX@0.0,restecg@0.0,AGE3@3.0>class@0"],\n', '["SEX@0.0,fbs@0.0,restecg@0.0,AGE3@3.0>class@0"],\n', '["SEX@0.0,restecg@0.0,exang@0.0,AGE3@3.0>class@0"],\n', '["SEX@0.0,fbs@0.0,restecg@0.0,exang@0.0,AGE3@3.0>class@0"],\n', '["SEX@0.0>class@0"],\n', '["SEX@0.0,AGE2@0.0>class@0"],\n', '["SEX@0.0,exang@0.0,AGE2@0.0>class@0"],\n', '["SEX@0.0,fbs@0.0,exang@0.0,AGE2@0.0>class@0"],\n', '["SEX@0.0,fbs@0.0,AGE2@0.0>class@0"],\n', '["SEX@0.0,exang@0.0>class@0"],\n', '["SEX@0.0,fbs@0.0,exang@0.0>class@0"],\n', '["SEX@0.0,fbs@0.0>class@0"],\n', '["SEX@0.0,AGE3@3.0>class@0"],\n', '["SEX@0.0,AGE2@0.0,AGE3@3.0>class@0"],\n', '["SEX@0.0,exang@0.0,AGE2@0.0,AGE3@3.0>class@0"],\n', '["SEX@0.0,fbs@0.0,exang@0.0,AGE2@0.0,AGE3@3.0>class@0"],\n', '["SEX@0.0,fbs@0.0,AGE2@0.0,AGE3@3.0>class@0"],\n', '["SEX@0.0,exang@0.0,AGE3@3.0>class@0"],\n', '["SEX@0.0,fbs@0.0,exang@0.0,AGE3@3.0>class@0"],\n', '["SEX@0.0,fbs@0.0,AGE3@3.0>class@0"],\n', '["exang@1.0,AGE3@7.0>class@1"],\n', '["restecg@2.0,exang@1.0,AGE3@7.0>class@1"],\n', '["exang@1.0,AGE1@2.0,AGE3@7.0>class@1"],\n', '["SEX@1.0,exang@1.0,AGE1@2.0,AGE3@7.0>class@1"],\n', '["fbs@0.0,exang@1.0,AGE1@2.0,AGE3@7.0>class@1"],\n', '["cp@4.0,exang@1.0,AGE1@2.0,AGE3@7.0>class@1"],\n', '["cp@4.0,fbs@0.0,exang@1.0,AGE1@2.0,AGE3@7.0>class@1"],\n', '["fbs@0.0,exang@1.0,AGE3@7.0>class@1"],\n', '["SEX@1.0,exang@1.0,AGE3@7.0>class@1"],\n', '["SEX@1.0,fbs@0.0,exang@1.0,AGE3@7.0>class@1"],\n', '["cp@4.0,exang@1.0,AGE3@7.0>class@1"],\n', '["SEX@1.0,cp@4.0,exang@1.0,AGE3@7.0>class@1"],\n', '["SEX@1.0,cp@4.0,fbs@0.0,exang@1.0,AGE3@7.0>class@1"],\n', '["cp@4.0,fbs@0.0,exang@1.0,AGE3@7.0>class@1"],\n', '["exang@1.0>class@1"],\n', '["restecg@0.0,exang@1.0>class@1"],\n', '["restecg@2.0,exang@1.0>class@1"],\n', '["fbs@0.0,restecg@2.0,exang@1.0>class@1"],\n', '["SEX@1.0,restecg@2.0,exang@1.0>class@1"],\n', '["SEX@1.0,fbs@0.0,restecg@2.0,exang@1.0>class@1"],\n', '["exang@1.0,AGE1@2.0>class@1"],\n', '["restecg@2.0,exang@1.0,AGE1@2.0>class@1"],\n', '["SEX@1.0,exang@1.0,AGE1@2.0>class@1"],\n', '["SEX@1.0,fbs@0.0,exang@1.0,AGE1@2.0>class@1"],\n', '["fbs@0.0,exang@1.0,AGE1@2.0>class@1"],\n', '["cp@4.0,exang@1.0,AGE1@2.0>class@1"],\n', '["cp@4.0,restecg@2.0,exang@1.0,AGE1@2.0>class@1"],\n', '["SEX@1.0,cp@4.0,exang@1.0,AGE1@2.0>class@1"],\n', '["SEX@1.0,cp@4.0,fbs@0.0,exang@1.0,AGE1@2.0>class@1"],\n', '["cp@4.0,fbs@0.0,exang@1.0,AGE1@2.0>class@1"],\n', '["SEX@1.0,exang@1.0>class@1"],\n', '["SEX@1.0,fbs@0.0,exang@1.0>class@1"],\n', '["fbs@0.0,exang@1.0>class@1"],\n', '["cp@4.0,exang@1.0>class@1"],\n', '["cp@4.0,restecg@2.0,exang@1.0>class@1"],\n', '["cp@4.0,fbs@0.0,restecg@2.0,exang@1.0>class@1"],\n', '["SEX@1.0,cp@4.0,restecg@2.0,exang@1.0>class@1"],\n', '["SEX@1.0,cp@4.0,fbs@0.0,restecg@2.0,exang@1.0>class@1"],\n', '["SEX@1.0,cp@4.0,exang@1.0>class@1"],\n', '["SEX@1.0,cp@4.0,fbs@0.0,exang@1.0>class@1"],\n', '["cp@4.0,fbs@0.0,exang@1.0>class@1"],\n', '["restecg@0.0,AGE0@0.0,AGE3@3.0>class@0"],\n', '["restecg@0.0,AGE0@0.0,AGE2@0.0,AGE3@3.0>class@0"],\n', '["fbs@0.0,restecg@0.0,AGE0@0.0,AGE3@3.0>class@0"],\n', '["restecg@0.0,exang@0.0,AGE0@0.0,AGE3@3.0>class@0"],\n', '["fbs@0.0,restecg@0.0,exang@0.0,AGE0@0.0,AGE3@3.0>class@0"],\n', '["restecg@0.0,AGE0@0.0>class@0"],\n', '["restecg@0.0,AGE0@0.0,AGE2@0.0>class@0"],\n', '["fbs@0.0,restecg@0.0,AGE0@0.0,AGE2@0.0>class@0"],\n', '["restecg@0.0,exang@0.0,AGE0@0.0,AGE2@0.0>class@0"],\n', '["fbs@0.0,restecg@0.0,AGE0@0.0>class@0"],\n', '["restecg@0.0,exang@0.0,AGE0@0.0>class@0"],\n', '["fbs@0.0,restecg@0.0,exang@0.0,AGE0@0.0>class@0"],\n', '["AGE0@0.0,AGE3@3.0>class@0"],\n', '["SEX@1.0,AGE0@0.0,AGE3@3.0>class@0"],\n', '["AGE0@0.0,AGE2@0.0,AGE3@3.0>class@0"],\n', '["SEX@1.0,AGE0@0.0,AGE2@0.0,AGE3@3.0>class@0"],\n', '["fbs@0.0,AGE0@0.0,AGE2@0.0,AGE3@3.0>class@0"],\n', '["exang@0.0,AGE0@0.0,AGE2@0.0,AGE3@3.0>class@0"],\n', '["fbs@0.0,exang@0.0,AGE0@0.0,AGE2@0.0,AGE3@3.0>class@0"],\n', '["fbs@0.0,AGE0@0.0,AGE3@3.0>class@0"],\n', '["exang@0.0,AGE0@0.0,AGE3@3.0>class@0"],\n', '["SEX@1.0,exang@0.0,AGE0@0.0,AGE3@3.0>class@0"],\n', '["fbs@0.0,exang@0.0,AGE0@0.0,AGE3@3.0>class@0"],\n', '["AGE0@0.0>class@0"],\n', '["SEX@1.0,AGE0@0.0>class@0"],\n', '["SEX@1.0,fbs@0.0,AGE0@0.0>class@0"],\n', '["AGE0@0.0,AGE2@0.0>class@0"],\n', '["SEX@1.0,AGE0@0.0,AGE2@0.0>class@0"],\n', '["SEX@1.0,fbs@0.0,AGE0@0.0,AGE2@0.0>class@0"],\n', '["fbs@0.0,AGE0@0.0,AGE2@0.0>class@0"],\n', '["exang@0.0,AGE0@0.0,AGE2@0.0>class@0"],\n', '["SEX@1.0,exang@0.0,AGE0@0.0,AGE2@0.0>class@0"],\n', '["SEX@1.0,fbs@0.0,exang@0.0,AGE0@0.0,AGE2@0.0>class@0"],\n', '["fbs@0.0,exang@0.0,AGE0@0.0,AGE2@0.0>class@0"],\n', '["fbs@0.0,AGE0@0.0>class@0"],\n', '["exang@0.0,AGE0@0.0>class@0"],\n', '["SEX@1.0,exang@0.0,AGE0@0.0>class@0"],\n', '["SEX@1.0,fbs@0.0,exang@0.0,AGE0@0.0>class@0"],\n', '["fbs@0.0,exang@0.0,AGE0@0.0>class@0"],\n', '["restecg@0.0,AGE0@0.0,AGE1@1.0,AGE3@3.0>class@0"],\n', '["restecg@0.0,exang@0.0,AGE0@0.0,AGE1@1.0,AGE3@3.0>class@0"],\n', '["restecg@0.0,AGE0@0.0,AGE1@1.0>class@0"],\n', '["restecg@0.0,AGE0@0.0,AGE1@1.0,AGE2@0.0>class@0"],\n', '["fbs@0.0,restecg@0.0,AGE0@0.0,AGE1@1.0>class@0"],\n', '["restecg@0.0,exang@0.0,AGE0@0.0,AGE1@1.0>class@0"],\n', '["fbs@0.0,restecg@0.0,exang@0.0,AGE0@0.0,AGE1@1.0>class@0"],\n', '["AGE0@0.0,AGE1@1.0,AGE3@3.0>class@0"],\n', '["SEX@1.0,AGE0@0.0,AGE1@1.0,AGE3@3.0>class@0"],\n', '["AGE0@0.0,AGE1@1.0,AGE2@0.0,AGE3@3.0>class@0"],\n', '["fbs@0.0,AGE0@0.0,AGE1@1.0,AGE2@0.0,AGE3@3.0>class@0"],\n', '["exang@0.0,AGE0@0.0,AGE1@1.0,AGE2@0.0,AGE3@3.0>class@0"],\n', '["fbs@0.0,exang@0.0,AGE0@0.0,AGE1@1.0,AGE2@0.0,AGE3@3.0,>class@0"],\n', '["fbs@0.0,AGE0@0.0,AGE1@1.0,AGE3@3.0>class@0"],\n', '["exang@0.0,AGE0@0.0,AGE1@1.0,AGE3@3.0>class@0"],\n', '["SEX@1.0,exang@0.0,AGE0@0.0,AGE1@1.0,AGE3@3.0>class@0"],\n', '["fbs@0.0,exang@0.0,AGE0@0.0,AGE1@1.0,AGE3@3.0>class@0"],\n', '["AGE0@0.0,AGE1@1.0>class@0"],\n', '["SEX@1.0,AGE0@0.0,AGE1@1.0>class@0"],\n', '["SEX@1.0,fbs@0.0,AGE0@0.0,AGE1@1.0>class@0"],\n', '["AGE0@0.0,AGE1@1.0,AGE2@0.0>class@0"],\n', '["SEX@1.0,AGE0@0.0,AGE1@1.0,AGE2@0.0>class@0"],\n', '["SEX@1.0,fbs@0.0,AGE0@0.0,AGE1@1.0,AGE2@0.0>class@0"],\n', '["fbs@0.0,AGE0@0.0,AGE1@1.0,AGE2@0.0>class@0"],\n', '["exang@0.0,AGE0@0.0,AGE1@1.0,AGE2@0.0>class@0"],\n', '["SEX@1.0,exang@0.0,AGE0@0.0,AGE1@1.0,AGE2@0.0>class@0"],\n', '["fbs@0.0,exang@0.0,AGE0@0.0,AGE1@1.0,AGE2@0.0>class@0"],\n', '["fbs@0.0,AGE0@0.0,AGE1@1.0>class@0"],\n', '["exang@0.0,AGE0@0.0,AGE1@1.0>class@0"],\n', '["SEX@1.0,exang@0.0,AGE0@0.0,AGE1@1.0>class@0"],\n', '["SEX@1.0,fbs@0.0,exang@0.0,AGE0@0.0,AGE1@1.0>class@0"],\n', '["fbs@0.0,exang@0.0,AGE0@0.0,AGE1@1.0>class@0"],\n', '["AGE3@7.0>class@0"],\n', '["AGE3@7.0>class@1"],\n', '["AGE2@0.0,AGE3@7.0>class@1"],\n', '["exang@0.0,AGE3@7.0>class@1"],\n', '["restecg@0.0,AGE3@7.0>class@1"],\n', '["fbs@0.0,restecg@0.0,AGE3@7.0>class@1"],\n', '["SEX@1.0,restecg@0.0,AGE3@7.0>class@1"],\n', '["restecg@2.0,AGE3@7.0>class@1"],\n', '["fbs@0.0,restecg@2.0,AGE3@7.0>class@1"],\n', '["SEX@1.0,restecg@2.0,AGE3@7.0>class@1"],\n', '["SEX@1.0,fbs@0.0,restecg@2.0,AGE3@7.0>class@1"],\n', '["AGE1@2.0,AGE3@7.0>class@1"],\n', '["restecg@2.0,AGE1@2.0,AGE3@7.0>class@1"],\n', '["SEX@1.0,restecg@2.0,AGE1@2.0,AGE3@7.0>class@1"],\n', '["fbs@0.0,restecg@2.0,AGE1@2.0,AGE3@7.0>class@1"],\n', '["cp@4.0,AGE1@2.0,AGE3@7.0>class@1"],\n', '["SEX@1.0,cp@4.0,AGE1@2.0,AGE3@7.0>class@1"],\n', '["SEX@1.0,cp@4.0,fbs@0.0,AGE1@2.0,AGE3@7.0>class@1"],\n', '["cp@4.0,fbs@0.0,AGE1@2.0,AGE3@7.0>class@1"],\n', '["SEX@1.0,AGE1@2.0,AGE3@7.0>class@1"],\n', '["SEX@1.0,fbs@0.0,AGE1@2.0,AGE3@7.0>class@1"],\n', '["fbs@0.0,AGE1@2.0,AGE3@7.0>class@1"],\n', '["cp@4.0,AGE3@7.0>class@1"],\n', '["cp@4.0,restecg@2.0,AGE3@7.0>class@1"],\n', '["SEX@1.0,cp@4.0,restecg@2.0,AGE3@7.0>class@1"],\n', '["cp@4.0,fbs@0.0,restecg@2.0,AGE3@7.0>class@1"],\n', '["SEX@1.0,cp@4.0,AGE3@7.0>class@1"],\n', '["SEX@1.0,cp@4.0,fbs@0.0,AGE3@7.0>class@1"],\n', '["cp@4.0,fbs@0.0,AGE3@7.0>class@1"],\n', '["fbs@0.0,AGE3@7.0>class@1"],\n', '["SEX@1.0,AGE3@7.0>class@1"],\n', '["SEX@1.0,fbs@0.0,AGE3@7.0>class@1"],\n', '["AGE1@1.0>class@1"],\n', '["SEX@1.0,AGE1@1.0>class@1"],\n', '["restecg@2.0,AGE1@1.0>class@0"],\n', '["restecg@2.0,exang@0.0,AGE1@1.0>class@0"],\n', '["fbs@0.0,restecg@2.0,AGE1@1.0>class@0"],\n', '["restecg@0.0,AGE1@1.0,AGE3@3.0>class@0"],\n', '["restecg@0.0,AGE1@1.0,AGE2@0.0,AGE3@3.0>class@0"],\n', '["fbs@0.0,restecg@0.0,AGE1@1.0,AGE2@0.0,AGE3@3.0>class@0"],\n', '["restecg@0.0,exang@0.0,AGE1@1.0,AGE2@0.0,AGE3@3.0>class@0"],\n', '["fbs@0.0,restecg@0.0,exang@0.0,AGE1@1.0,AGE2@0.0,AGE3@3.0,>class@0"],\n', '["fbs@0.0,restecg@0.0,AGE1@1.0,AGE3@3.0>class@0"],\n', '["restecg@0.0,exang@0.0,AGE1@1.0,AGE3@3.0>class@0"],\n', '["fbs@0.0,restecg@0.0,exang@0.0,AGE1@1.0,AGE3@3.0>class@0"],\n', '["restecg@0.0,AGE1@1.0>class@0"],\n', '["SEX@1.0,restecg@0.0,AGE1@1.0>class@0"],\n', '["SEX@1.0,fbs@0.0,restecg@0.0,AGE1@1.0>class@0"],\n', '["restecg@0.0,AGE1@1.0,AGE2@0.0>class@0"],\n', '["SEX@1.0,restecg@0.0,AGE1@1.0,AGE2@0.0>class@0"],\n', '["fbs@0.0,restecg@0.0,AGE1@1.0,AGE2@0.0>class@0"],\n', '["restecg@0.0,exang@0.0,AGE1@1.0,AGE2@0.0>class@0"],\n', '["fbs@0.0,restecg@0.0,exang@0.0,AGE1@1.0,AGE2@0.0>class@0"],\n', '["fbs@0.0,restecg@0.0,AGE1@1.0>class@0"],\n', '["restecg@0.0,exang@0.0,AGE1@1.0>class@0"],\n', '["SEX@1.0,restecg@0.0,exang@0.0,AGE1@1.0>class@0"],\n', '["fbs@0.0,restecg@0.0,exang@0.0,AGE1@1.0>class@0"],\n', '["AGE1@1.0,AGE3@3.0>class@0"],\n', '["SEX@1.0,AGE1@1.0,AGE3@3.0>class@0"],\n', '["SEX@1.0,fbs@0.0,AGE1@1.0,AGE3@3.0>class@0"],\n', '["AGE1@1.0,AGE2@0.0,AGE3@3.0>class@0"],\n', '["SEX@1.0,AGE1@1.0,AGE2@0.0,AGE3@3.0>class@0"],\n', '["SEX@1.0,fbs@0.0,AGE1@1.0,AGE2@0.0,AGE3@3.0>class@0"],\n', '["fbs@0.0,AGE1@1.0,AGE2@0.0,AGE3@3.0>class@0"],\n', '["exang@0.0,AGE1@1.0,AGE2@0.0,AGE3@3.0>class@0"],\n', '["SEX@1.0,exang@0.0,AGE1@1.0,AGE2@0.0,AGE3@3.0>class@0"],\n', '["SEX@1.0,fbs@0.0,exang@0.0,AGE1@1.0,AGE2@0.0,AGE3@3.0,>class@0"],\n', '["fbs@0.0,exang@0.0,AGE1@1.0,AGE2@0.0,AGE3@3.0>class@0"],\n', '["fbs@0.0,AGE1@1.0,AGE3@3.0>class@0"],\n', '["exang@0.0,AGE1@1.0,AGE3@3.0>class@0"],\n', '["SEX@1.0,exang@0.0,AGE1@1.0,AGE3@3.0>class@0"],\n', '["SEX@1.0,fbs@0.0,exang@0.0,AGE1@1.0,AGE3@3.0>class@0"],\n', '["fbs@0.0,exang@0.0,AGE1@1.0,AGE3@3.0>class@0"],\n', '["AGE1@1.0>class@0"],\n', '["SEX@1.0,AGE1@1.0>class@0"],\n', '["SEX@1.0,fbs@0.0,AGE1@1.0>class@0"],\n', '["AGE1@1.0,AGE2@0.0>class@0"],\n', '["SEX@1.0,AGE1@1.0,AGE2@0.0>class@0"],\n', '["SEX@1.0,fbs@0.0,AGE1@1.0,AGE2@0.0>class@0"],\n', '["fbs@0.0,AGE1@1.0,AGE2@0.0>class@0"],\n', '["exang@0.0,AGE1@1.0,AGE2@0.0>class@0"],\n', '["SEX@1.0,exang@0.0,AGE1@1.0,AGE2@0.0>class@0"],\n', '["SEX@1.0,fbs@0.0,exang@0.0,AGE1@1.0,AGE2@0.0>class@0"],\n', '["fbs@0.0,exang@0.0,AGE1@1.0,AGE2@0.0>class@0"],\n', '["fbs@0.0,AGE1@1.0>class@0"],\n', '["exang@0.0,AGE1@1.0>class@0"],\n', '["SEX@1.0,exang@0.0,AGE1@1.0>class@0"],\n', '["SEX@1.0,fbs@0.0,exang@0.0,AGE1@1.0>class@0"],\n', '["fbs@0.0,exang@0.0,AGE1@1.0>class@0"],\n', '["AGE3@3.0>class@1"],\n', '["fbs@0.0,AGE3@3.0>class@1"],\n', '["AGE2@0.0>class@1"],\n', '["SEX@1.0,AGE2@0.0>class@1"],\n', '["SEX@1.0,fbs@0.0,AGE2@0.0>class@1"],\n', '["fbs@0.0,AGE2@0.0>class@1"],\n', '["restecg@0.0>class@1"],\n', '["fbs@0.0,restecg@0.0>class@1"],\n', '["SEX@1.0,restecg@0.0>class@1"],\n', '["SEX@1.0,fbs@0.0,restecg@0.0>class@1"],\n', '["exang@0.0>class@1"],\n', '["SEX@1.0,exang@0.0>class@1"],\n', '["SEX@1.0,fbs@0.0,exang@0.0>class@1"],\n', '["fbs@0.0,exang@0.0>class@1"],\n', '["restecg@2.0>class@1"],\n', '["restecg@2.0,exang@0.0>class@1"],\n', '["fbs@0.0,restecg@2.0,exang@0.0>class@1"],\n', '["fbs@0.0,restecg@2.0>class@1"],\n', '["SEX@1.0,restecg@2.0>class@1"],\n', '["SEX@1.0,fbs@0.0,restecg@2.0>class@1"],\n', '["AGE1@2.0>class@1"],\n', '["exang@0.0,AGE1@2.0>class@1"],\n', '["restecg@0.0,AGE1@2.0>class@1"],\n', '["restecg@2.0,AGE1@2.0>class@1"],\n', '["fbs@0.0,restecg@2.0,AGE1@2.0>class@1"],\n', '["SEX@1.0,restecg@2.0,AGE1@2.0>class@1"],\n', '["SEX@1.0,fbs@0.0,restecg@2.0,AGE1@2.0>class@1"],\n', '["cp@4.0,AGE1@2.0>class@1"],\n', '["cp@4.0,restecg@2.0,AGE1@2.0>class@1"],\n', '["cp@4.0,fbs@0.0,restecg@2.0,AGE1@2.0>class@1"],\n', '["SEX@1.0,cp@4.0,restecg@2.0,AGE1@2.0>class@1"],\n', '["SEX@1.0,cp@4.0,fbs@0.0,restecg@2.0,AGE1@2.0>class@1"],\n', '["SEX@1.0,cp@4.0,AGE1@2.0>class@1"],\n', '["SEX@1.0,cp@4.0,fbs@0.0,AGE1@2.0>class@1"],\n', '["cp@4.0,fbs@0.0,AGE1@2.0>class@1"],\n', '["SEX@1.0,AGE1@2.0>class@1"],\n', '["SEX@1.0,fbs@0.0,AGE1@2.0>class@1"],\n', '["fbs@0.0,AGE1@2.0>class@1"],\n', '["cp@4.0>class@1"],\n', '["cp@4.0,AGE2@0.0>class@1"],\n', '["cp@4.0,exang@0.0>class@1"],\n', '["cp@4.0,restecg@0.0>class@1"],\n', '["SEX@1.0,cp@4.0,restecg@0.0>class@1"],\n', '["cp@4.0,fbs@0.0,restecg@0.0>class@1"],\n', '["cp@4.0,restecg@2.0>class@1"],\n', '["SEX@1.0,cp@4.0,restecg@2.0>class@1"],\n', '["SEX@1.0,cp@4.0,fbs@0.0,restecg@2.0>class@1"],\n', '["cp@4.0,fbs@0.0,restecg@2.0>class@1"],\n', '["SEX@1.0,cp@4.0>class@1"],\n', '["SEX@1.0,cp@4.0,fbs@0.0>class@1"],\n', '["cp@4.0,fbs@0.0>class@1"],\n', '["SEX@1.0>class@1"],\n', '["SEX@1.0,fbs@0.0>class@1"],\n', '["fbs@0.0>class@1"],\n', '["AGE1@2.0>class@0"],\n', '["exang@0.0,AGE1@2.0>class@0"],\n', '["fbs@0.0,exang@0.0,AGE1@2.0>class@0"],\n', '["AGE1@2.0,AGE2@0.0>class@0"],\n', '["exang@0.0,AGE1@2.0,AGE2@0.0>class@0"],\n', '["fbs@0.0,exang@0.0,AGE1@2.0,AGE2@0.0>class@0"],\n', '["fbs@0.0,AGE1@2.0,AGE2@0.0>class@0"],\n', '["fbs@0.0,AGE1@2.0>class@0"],\n', '["AGE1@2.0,AGE3@3.0>class@0"],\n', '["exang@0.0,AGE1@2.0,AGE3@3.0>class@0"],\n', '["AGE1@2.0,AGE2@0.0,AGE3@3.0>class@0"],\n', '["fbs@0.0,AGE1@2.0,AGE2@0.0,AGE3@3.0>class@0"],\n', '["fbs@0.0,AGE1@2.0,AGE3@3.0>class@0"],\n', '["cp@4.0>class@0"],\n', '["cp@4.0,fbs@0.0>class@0"],\n', '["cp@4.0,AGE2@0.0>class@0"],\n', '["cp@4.0,fbs@0.0,AGE2@0.0>class@0"],\n', '["restecg@0.0,AGE3@3.0>class@0"],\n', '["SEX@1.0,restecg@0.0,AGE3@3.0>class@0"],\n', '["restecg@0.0,AGE2@0.0,AGE3@3.0>class@0"],\n', '["restecg@0.0,exang@0.0,AGE2@0.0,AGE3@3.0>class@0"],\n', '["fbs@0.0,restecg@0.0,exang@0.0,AGE2@0.0,AGE3@3.0>class@0"],\n', '["fbs@0.0,restecg@0.0,AGE2@0.0,AGE3@3.0>class@0"],\n', '["fbs@0.0,restecg@0.0,AGE3@3.0>class@0"],\n', '["restecg@0.0,exang@0.0,AGE3@3.0>class@0"],\n', '["fbs@0.0,restecg@0.0,exang@0.0,AGE3@3.0>class@0"],\n', '["restecg@0.0>class@0"],\n', '["SEX@1.0,restecg@0.0>class@0"],\n', '["SEX@1.0,fbs@0.0,restecg@0.0>class@0"],\n', '["restecg@0.0,AGE2@0.0>class@0"],\n', '["SEX@1.0,restecg@0.0,AGE2@0.0>class@0"],\n', '["SEX@1.0,fbs@0.0,restecg@0.0,AGE2@0.0>class@0"],\n', '["fbs@0.0,restecg@0.0,AGE2@0.0>class@0"],\n', '["restecg@0.0,exang@0.0,AGE2@0.0>class@0"],\n', '["SEX@1.0,restecg@0.0,exang@0.0,AGE2@0.0>class@0"],\n', '["fbs@0.0,restecg@0.0,exang@0.0,AGE2@0.0>class@0"],\n', '["fbs@0.0,restecg@0.0>class@0"],\n', '["restecg@0.0,exang@0.0>class@0"],\n', '["SEX@1.0,restecg@0.0,exang@0.0>class@0"],\n', '["SEX@1.0,fbs@0.0,restecg@0.0,exang@0.0>class@0"],\n', '["fbs@0.0,restecg@0.0,exang@0.0>class@0"],\n', '["restecg@2.0>class@0"],\n', '["SEX@1.0,restecg@2.0>class@0"],\n', '["SEX@1.0,fbs@0.0,restecg@2.0>class@0"],\n', '["restecg@2.0,AGE2@0.0>class@0"],\n', '["SEX@1.0,restecg@2.0,AGE2@0.0>class@0"],\n', '["restecg@2.0,exang@0.0,AGE2@0.0>class@0"],\n', '["SEX@1.0,restecg@2.0,exang@0.0,AGE2@0.0>class@0"],\n', '["fbs@0.0,restecg@2.0,exang@0.0,AGE2@0.0>class@0"],\n', '["fbs@0.0,restecg@2.0,AGE2@0.0>class@0"],\n', '["restecg@2.0,exang@0.0>class@0"],\n', '["SEX@1.0,restecg@2.0,exang@0.0>class@0"],\n', '["fbs@0.0,restecg@2.0,exang@0.0>class@0"],\n', '["fbs@0.0,restecg@2.0>class@0"],\n', '["restecg@2.0,AGE3@3.0>class@0"],\n', '["restecg@2.0,AGE2@0.0,AGE3@3.0>class@0"],\n', '["restecg@2.0,exang@0.0,AGE2@0.0,AGE3@3.0>class@0"],\n', '["fbs@0.0,restecg@2.0,exang@0.0,AGE2@0.0,AGE3@3.0>class@0"],\n', '["fbs@0.0,restecg@2.0,AGE2@0.0,AGE3@3.0>class@0"],\n', '["restecg@2.0,exang@0.0,AGE3@3.0>class@0"],\n', '["fbs@0.0,restecg@2.0,exang@0.0,AGE3@3.0>class@0"],\n', '["fbs@0.0,restecg@2.0,AGE3@3.0>class@0"],\n', '["AGE3@3.0>class@0"],\n', '["SEX@1.0,AGE3@3.0>class@0"],\n', '["SEX@1.0,fbs@0.0,AGE3@3.0>class@0"],\n', '["AGE2@0.0,AGE3@3.0>class@0"],\n', '["SEX@1.0,AGE2@0.0,AGE3@3.0>class@0"],\n', '["SEX@1.0,fbs@0.0,AGE2@0.0,AGE3@3.0>class@0"],\n', '["exang@0.0,AGE2@0.0,AGE3@3.0>class@0"],\n', '["SEX@1.0,exang@0.0,AGE2@0.0,AGE3@3.0>class@0"],\n', '["SEX@1.0,fbs@0.0,exang@0.0,AGE2@0.0,AGE3@3.0>class@0"],\n', '["fbs@0.0,exang@0.0,AGE2@0.0,AGE3@3.0>class@0"],\n', '["fbs@0.0,AGE2@0.0,AGE3@3.0>class@0"],\n', '["exang@0.0,AGE3@3.0>class@0"],\n', '["SEX@1.0,exang@0.0,AGE3@3.0>class@0"],\n', '["SEX@1.0,fbs@0.0,exang@0.0,AGE3@3.0>class@0"],\n', '["fbs@0.0,exang@0.0,AGE3@3.0>class@0"],\n', '["fbs@0.0,AGE3@3.0>class@0"],\n', '["SEX@1.0>class@0"],\n', '["SEX@1.0,fbs@0.0>class@0"],\n', '["AGE2@0.0>class@0"],\n', '["SEX@1.0,AGE2@0.0>class@0"],\n', '["SEX@1.0,fbs@0.0,AGE2@0.0>class@0"],\n', '[

In [ ]:
f = open('/content/drive/MyDrive/Clev_DataSet/RPGrowth/unexpected_rule_file_mapped.txt','w')
for line in lst:
    f.write(line)
f.close()